package loc

// CostTab is the COST_TAB definition
type CostTab struct {
	UPCCode                  string  `sil:"F01,zeropad"`
	UPCCodeFormat            *int    `sil:"F07"`
	StatusCode               *string `sil:"F08"`
	TargetIdentifier         string  `sil:"F1000"`
	RecordStatus             int     `sil:"F1001" default:"1"`
	ActiveVendor             *string `sil:"F1037"`
	NextCostEvent            *string `sil:"F1038"`
	CostFeeAmount            *string `sil:"F1121"`
	CostFeePercent           *string `sil:"F1122"`
	UnitNetCost              *string `sil:"F1140"`
	OperatorResponsible      *int    `sil:"F1168"`
	BuyingFormat             *string `sil:"F1184"`
	SplitCaseCost            *string `sil:"F120"`
	AlternateItemCode        *string `sil:"F127"`
	SequenceNumber           *int    `sil:"F131"`
	SplitCaseCostStartDate   *string `sil:"F134"`
	NextCostNet              *string `sil:"F151"`
	NextCostStartDate        *string `sil:"F152"`
	AllowanceQualifier       *string `sil:"F156"`
	VendorBrokerNumber       *string `sil:"F165"`
	AllowancePercent         *string `sil:"F1657"`
	DiscountAmount           *string `sil:"F1658"`
	DiscountOffInvoice       *string `sil:"F1659"`
	RebateOffInvoice         *string `sil:"F1660"`
	CostBreakOffInvoice      *string `sil:"F1661"`
	BillBack1Amount          *string `sil:"F1662"`
	BillBack1Percent         *string `sil:"F1663"`
	BillBack2Amount          *string `sil:"F1664"`
	BillBack2Percent         *string `sil:"F1665"`
	BillBack3Amount          *string `sil:"F1666"`
	BillBack3Percent         *string `sil:"F1667"`
	BillBack4Descriptor      *string `sil:"F1668"`
	BillBack4Amount          *string `sil:"F1669"`
	BillBack4Percent         *string `sil:"F1670"`
	BackOrderDays            *int    `sil:"F1685"`
	MaintenanceOperatorLevel *int    `sil:"F1759"`
	MinimumCases             *string `sil:"F1760"`
	MinimumCubic             *string `sil:"F1761"`
	ReturnFees               *string `sil:"F1766"`
	CostMethod               *string `sil:"F1791"`
	SpareFieldCOS2           *string `sil:"F1792"`
	DeliveryDays             *int    `sil:"F1793"`
	DeliveryCycleDays        *int    `sil:"F1794"`
	SplitItemQty             *string `sil:"F1795"`
	LastAverageCost          *string `sil:"F1796"`
	SpareRECREGGCOST         *string `sil:"F1797"`
	CostForSupplier          *string `sil:"F1798"`
	HalfCaseCost             *string `sil:"F185"`
	InventoryMode            *string `sil:"F1875"`
	BuyingFormat             *string `sil:"F1887"`
	CaseSize                 *string `sil:"F19"`
	LastReceivingPackSize    *string `sil:"F194"`
	LastBaseCost             *string `sil:"F195"`
	CaseNetCost              *string `sil:"F196"`
	ReturnPolicy             *string `sil:"F1961"`
	StoreResponsible         *string `sil:"F1964"`
	DiscountQualifier        *string `sil:"F1973"`
	RebateQualifier          *string `sil:"F1974"`
	CostBreakQualifier       *string `sil:"F1975"`
	CostComment              *string `sil:"F1976"`
	AllowanceMinQty          *string `sil:"F1977"`
	DiscountMinQty           *string `sil:"F1978"`
	RebateMinQty             *string `sil:"F1979"`
	ReceivingPackSize        *string `sil:"F20"`
	AllowanceAmount          *string `sil:"F201"`
	AllowanceStartDate       *string `sil:"F202"`
	AllowanceEndDate         *string `sil:"F203"`
	AllowanceCode            *string `sil:"F204"`
	PrintLabelOnNextBatch    *string `sil:"F2119"`
	BaseCostTime             *string `sil:"F212"`
	AvailabilityDate         *string `sil:"F216"`
	CostBreakEndDate         *string `sil:"F219"`
	SplitItemCode            *string `sil:"F220"`
	AllowanceNumber          *string `sil:"F222"`
	AllowanceOffInvoice      *string `sil:"F223"`
	CostBreakMinQty          *string `sil:"F224"`
	CostBreakAmount          *string `sil:"F225"`
	CostBreakPercent         *string `sil:"F226"`
	CostBreakStartDate       *string `sil:"F227"`
	DiscountPercent          *string `sil:"F228"`
	DiscountStartDate        *string `sil:"F229"`
	DiscountEndDate          *string `sil:"F230"`
	DiscountNumber           *string `sil:"F231"`
	RebateAmount             *string `sil:"F233"`
	RebateStartDate          *string `sil:"F234"`
	RebateEndDate            *string `sil:"F235"`
	RebateNumber             *string `sil:"F236"`
	RebatePercent            *string `sil:"F237"`
	LastChangeDate           string  `sil:"F253" default:"NOW"`
	DiscountMaxQty           *string `sil:"F2566"`
	RebateMaxQty             *string `sil:"F2567"`
	CostBreakMaxQty          *string `sil:"F2568"`
	VendorCode               *string `sil:"F26"`
	VendorSubstitutionPolicy *string `sil:"F2601"`
	SPARERECREGGCOST         *int    `sil:"F2624"`
	SPARERECREGFCOST         *string `sil:"F2626"`
	SPARERECREGFCOST         *string `sil:"F2628"`
	DefaultQuantity          *string `sil:"F2666"`
	CostMethodDate           *string `sil:"F2699"`
	VendorId                 *string `sil:"F27"`
	CaseUPCCode              *string `sil:"F28"`
	PalletCases              *string `sil:"F325"`
	PalletLayers             *string `sil:"F326"`
	FreightCaseWeight        *string `sil:"F327"`
	FreightCaseCube          *string `sil:"F328"`
	AllowanceMaxQty          *string `sil:"F329"`
	BaseCost                 *string `sil:"F38"`
	BaseCostDate             *string `sil:"F39"`
	VendorAuthorizedItem     *string `sil:"F90"`
	BatchIdentifier          *string `sil:"F902"`
}
