package loc

// RecHdrSav is the REC_HDR_SAV definition
type RecHdrSav struct {
	TransactionNumber       *int    `sil:"F1032"`
	MovementStartTime       *string `sil:"F1035"`
	MovementEndTime         *string `sil:"F1036"`
	TerminalStore           string  `sil:"F1056"`
	TerminalNumber          *string `sil:"F1057"`
	RegistrationMode        *string `sil:"F1067"`
	TransactionMode         *string `sil:"F1068"`
	LineNumber              *int    `sil:"F1101"`
	UserNumber              *int    `sil:"F1126"`
	UserShortName           *string `sil:"F1127"`
	CustomerID              *string `sil:"F1148"`
	OperatorResponsible     *int    `sil:"F1168"`
	ReferenceNumber         *string `sil:"F1245"`
	DateDelivery            *string `sil:"F1246"`
	TransactionNote         *string `sil:"F1254"`
	TransBatchFileName      *string `sil:"F1255"`
	DateCreation            string  `sil:"F1264" default:"NOW"`
	TransactionArchive      *string `sil:"F1505"`
	ShipIDNumber            *string `sil:"F1642"`
	ShipName                *string `sil:"F1643"`
	ShipContactName         *string `sil:"F1644"`
	ShipAddressLine1        *string `sil:"F1645"`
	ShipAddressLine2        *string `sil:"F1646"`
	ShipAddressCity         *string `sil:"F1647"`
	ShipAddressState        *string `sil:"F1648"`
	ShipAddressZip          *string `sil:"F1649"`
	ShipPhoneVoice          *string `sil:"F1650"`
	ShipPhoneFax            *string `sil:"F1651"`
	ShipProductCategories   *string `sil:"F1652"`
	DateShipping            *string `sil:"F1653"`
	FreightRateWeight       *string `sil:"F1654"`
	FreightRateVolume       *string `sil:"F1655"`
	VendorTermDescriptor    *string `sil:"F1656"`
	BackOrderDays           *int    `sil:"F1685"`
	OperatorOrderPrinted    *int    `sil:"F1686"`
	OperatorReceiptPrinted  *int    `sil:"F1687"`
	OperatorInvoicePrinted  *int    `sil:"F1688"`
	OperatorExportMade      *int    `sil:"F1689"`
	ShippingNote            *string `sil:"F1692"`
	OperatorOrderEntered    *int    `sil:"F1693"`
	OperatorReceiptConfirm  *int    `sil:"F1694"`
	OperatorInvoiceEntered  *int    `sil:"F1695"`
	OperatorTrucker         *int    `sil:"F1696"`
	MinimumCases            *string `sil:"F1760"`
	MinimumCubic            *string `sil:"F1761"`
	DeliveryDays            *int    `sil:"F1793"`
	MinimumWeight           *string `sil:"F1883"`
	MinimumDollars          *string `sil:"F1884"`
	VendorContact2          *string `sil:"F1889"`
	VendorContact2Phone     *string `sil:"F1890"`
	LastChangeDate          string  `sil:"F253" default:"NOW"`
	DateEnd                 *string `sil:"F254"`
	DatePayable             *string `sil:"F2596"`
	CurrencyExchangeNow     *string `sil:"F2598"`
	CurrencyExchangeOrder   *string `sil:"F2599"`
	OperatorPickupPrinted   *int    `sil:"F2632"`
	OrderTime               *string `sil:"F2655"`
	DeliveryTime            *string `sil:"F2656"`
	EventDate               *string `sil:"F2657"`
	InvisibleOnPDA          *string `sil:"F2658"`
	DocumentSubType         *string `sil:"F2659"`
	VendorID                *string `sil:"F27"`
	AssociatedTaxRates      *string `sil:"F2710"`
	TransactionComment      *string `sil:"F2848"`
	TimestampTransArchive   *string `sil:"F2890"`
	VendorName              *string `sil:"F334"`
	VendorContactName       *string `sil:"F335"`
	VendorAddressLine1      *string `sil:"F336"`
	VendorAddressLine2      *string `sil:"F337"`
	VendorAddressCity       *string `sil:"F338"`
	VendorAddressState      *string `sil:"F339"`
	VendorAddressZip        *string `sil:"F340"`
	VendorPhoneVoice        *string `sil:"F341"`
	VendorPhoneFax          *string `sil:"F342"`
	VendorProductCategories *string `sil:"F343"`
	FreightbrokerCompany    *string `sil:"F344"`
	FOBPoint                *string `sil:"F345"`
	VendorLimit             *string `sil:"F346"`
	SpecialDiscountPercent  *string `sil:"F347"`
	TermsDays               *int    `sil:"F348"`
	TermsDiscountPercent    *string `sil:"F349"`
	VendorAccount           *string `sil:"F352"`
	DateOrder               *string `sil:"F76"`
	BatchIDentifier         *string `sil:"F902"`
	PurchaseOrderNumber     *string `sil:"F91"`
}
