package loc

// SclNutTab is the SCL_NUT_TAB definition
type SclNutTab struct {
	SubDepartmentCode              *int    `sil:"F04"`
	TargetIDentifier               string  `sil:"F1000" default:"PAL"`
	RecordStatus                   int     `sil:"F1001" default:"1"`
	MaintenanceOperatorLevel       *int    `sil:"F1759"`
	StoreResponsible               *string `sil:"F1964"`
	LowCholesterolIndicator        *string `sil:"F197"`
	LowFatIndicator                *string `sil:"F198"`
	LowSodiumIndicator             *string `sil:"F199"`
	LowCaloriesIndicator           *string `sil:"F200"`
	NutrifactLabelFormat           *string `sil:"F2500"`
	Thiamine                       *string `sil:"F2501"`
	Riboflavin                     *string `sil:"F2502"`
	Niacin                         *string `sil:"F2503"`
	VitaminD                       *string `sil:"F2504"`
	VitaminE                       *string `sil:"F2505"`
	VitaminB6                      *string `sil:"F2506"`
	FolicAcid                      *string `sil:"F2507"`
	VitaminB12                     *string `sil:"F2508"`
	Phosphorus                     *string `sil:"F2509"`
	Iodine                         *string `sil:"F2510"`
	Magnesium                      *string `sil:"F2511"`
	Zinc                           *string `sil:"F2512"`
	Copper                         *string `sil:"F2513"`
	Biotin                         *string `sil:"F2514"`
	PantothenicAcid                *string `sil:"F2515"`
	BetaCarotene                   *string `sil:"F2516"`
	Chloride                       *string `sil:"F2517"`
	Chromium                       *string `sil:"F2518"`
	Manganese                      *string `sil:"F2519"`
	Molybdenum                     *string `sil:"F2520"`
	Selenium                       *string `sil:"F2521"`
	VitaminK                       *string `sil:"F2522"`
	DietaryFiberPercent            *string `sil:"F2523"`
	NutrifactDescription           *string `sil:"F2524"`
	Potassium                      *string `sil:"F2525"`
	PercentagePotassium            *string `sil:"F2526"`
	TransFatAcid                   *string `sil:"F2527"`
	CaloriesFromSaturatedFat       *string `sil:"F2528"`
	OtherCarbohydrates             *string `sil:"F2529"`
	LastChangeDate                 string  `sil:"F253" default:"NOW"`
	MonoUnsaturatedFat             *string `sil:"F2530"`
	PolyUnsaturatedFat             *string `sil:"F2531"`
	InsolubleFiber                 *string `sil:"F2532"`
	SolubleFiber                   *string `sil:"F2533"`
	SugarAlcohol                   *string `sil:"F2534"`
	SaturatedFatTransFat           *string `sil:"F2535"`
	PercentageSaturatedFatTransFat *string `sil:"F2536"`
	CaloriesFromSaturatedTrans     *string `sil:"F2537"`
	Energy                         *string `sil:"F2538"`
	Omega6PolyunsaturatedFat       *string `sil:"F2539"`
	Omega3PolyunsaturatedFat       *string `sil:"F2540"`
	Starch                         *string `sil:"F2541"`
	TemplateNumber                 *string `sil:"F268"`
	ServingSize                    *string `sil:"F276"`
	ServingsPerContainer           *string `sil:"F277"`
	Calories                       *string `sil:"F278"`
	CaloriesFromFat                *string `sil:"F279"`
	TotalFatGrams                  *string `sil:"F280"`
	TotalFatPercent                *string `sil:"F281"`
	SaturatedFatGrams              *string `sil:"F282"`
	SaturatedFatPercent            *string `sil:"F283"`
	CholesterolMilligrams          *string `sil:"F284"`
	CholesterolPercent             *string `sil:"F285"`
	CertifiedOrganic               *string `sil:"F2852"`
	OrganicIngredients             *string `sil:"F2853"`
	PesticideFree                  *string `sil:"F2854"`
	WildCrafted                    *string `sil:"F2855"`
	Biodynamic                     *string `sil:"F2856"`
	LocallyProduced                *string `sil:"F2857"`
	GlutenFree                     *string `sil:"F2858"`
	NonDiary                       *string `sil:"F2859"`
	SodiumMilligrams               *string `sil:"F286"`
	SodiumPercent                  *string `sil:"F287"`
	TotalCarbohydratesMilligrams   *string `sil:"F288"`
	TotalCarbohydratesPercent      *string `sil:"F289"`
	DietaryFiberGrams              *string `sil:"F290"`
	SugarsGrams                    *string `sil:"F291"`
	ProteinGrams                   *string `sil:"F292"`
	VitaminAPercent                *string `sil:"F293"`
	VitaminCPercent                *string `sil:"F294"`
	CalciumPercent                 *string `sil:"F295"`
	NutritionPortion               *int    `sil:"F2951"`
	IronPercent                    *string `sil:"F296"`
	BatchIDentifier                *string `sil:"F902"`
}
